# Generated by Django 4.2.26 on 2025-11-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_post_updated_at_post_image_alter_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='on_delete',
            new_name='post',
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
